[package]
name = "autoclicker"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31"
enigo = "0.5"
device_query = "3"
crossbeam-channel = "0.5"

[target.'cfg(target_os = "macos")'.dependencies]
tray-icon = "0.20"
